
title: Anna Gassen
url: 'http://astroanna.github.com'
baseurl: '/online-cv' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#default blue
#style: styles-2 #green
style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Anna Gassen
tagline: Aspiring Computer Scientist
pic: annaFace.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: annagassen@me.com
phone: 415 308 0442
website: blog.webjeda.com #do not add http://
linkedin: annagassen
github: astroanna
twitter: '@anna_gassen'


# Tracker
analytics: UA-83979019-1
#Update all the sections by editing the files inside _includes folder.
